services:
  - type: web
    name: movie-sentiment-analysis
    env: python
    plan: free
    runtime: python-3.11.8
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app